name: hello world

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *" # Execute every 5 minutes


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display hello world message
        run: echo "hello world, felipe"

      - name: Another task
        run: echo "another task"
