name: hello world

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display hello world message
        run: echo "hello world, felipe"

      - name: Another task
        run: echo "another task"
