name: hello world

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # schedule:
  #   - cron: "*/5 * * * *" # Execute every 5 minutes


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display hello world message
        run: echo "hello world, felipe"

      - name: Another task
        run: echo "another task"

      - name: Checkout
        uses: actions/checkout@v6-beta

      - name: List the files of the repo
        run:
          echo "The repository ${{github.repository}} contains the following files:"
          tree
